spring.application.name=datascraper

input.scraper.xlsx.files[0]=classpath:trollfarm.xlsx
input.scraper.xlsx.files[1]=classpath:trollok-20260407.xlsx

output.json.path=file:../../src/assets/datasources/telex/profiles.json

