name: Run Data scapers and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  run-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build project
        run: ./tools/telex-data-scraper/mvnw clean install -DskipTests

      - name: Run Data scraper tool
        run: ./tools/telex-data-scraper/mvnw spring-boot:run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-update generated files"
          committer: github-actions <github-actions@github.com>
          author: github-actions <github-actions@github.com>
          branch: auto/update-generated-files
          delete-branch: true
          title: "Automated profile-json update"
          body: |
            This PR was automatically generated by a GitHub Action.

            It runs the data scraper spring boot application that updates the profiles.json.
          labels: |
            automated
            bot